### ISSUE TITLE
Suspicious radius/altitude results for planetocentric and planetodetic calculations

### ISSUE THREAD

**Issue by szabolcsvelkei** [IO-Aerospace-software-engineering/Astrodynamics#193]
**Describe the bug**
Suspicious radius/altitude results for planetocentric and planetodetic calculations

**To Reproduce**
Use an observation site for example from here:
https://www.jostjahn.de/stations/W57.html
https://www.jostjahn.de/stations/K88.html
Calculate plantetocentric values from planetodetic or vice versa
Result:
Wrong radius/altitude

**Expected behavior**
Precise numbers (~rounding errors)

**Screenshots**
N.A.

**Desktop (please complete the following information):**
 - OS: Windows]
 - Version latest* 4.1.0

**Additional context**
N.A.

**Comment by sylvain-guillet** [comment]
Hi @szabolcsvelkei, thanks for your feedback.

I studied your problem and here is my explanation:

I first created planetodetic and planetographic coordinates, converted one to the other, then compared the result with JPL WebGeocalc (https://wgc.jpl.nasa.gov:8443/webgeocalc/#StateVector) and the results are strictly the same.

When I look at the result on your site, I think the "Altitude" property refers to the AMSL Altitude (Above mean sea level) but IO Framework uses the definition given by JPL: "altitude is the altitude of the point above the reference spheroid" (https://wgc.jpl.nasa.gov:8443/webgeocalc/documents/coordinateSystemHelp_L2.html) and this explains why we don't have the same result, it's because we don't use the same reference (Elipsoid vs Mean sea level)

That being said, I think the term "altitude" is confusing and many people expect the AMSL altitude, I could change the term Altitude to Geodesics Height to be more precise.

Today the framework does not provide a method to calculate the AMSL Altitude and this could be an interesting improvement for the next version.

Sylvain
